name: mammoth

ghc-options: -Wall

library:
  source-dirs:
    - src

executables:
  mammoth:
    main: exe/Main.hs
    dependencies:
      - mammoth

dependencies:
  - base
  - http-api-data
  - http-client
  - lens
  - influxdb
  - servant
  - servant-server
  - servant-swagger-ui
  - text
  - time
  - transformers
  - aeson
  - vector
  - wai
  - wai-extra
  - warp
